config/routes.rb
Calabouco::Application.routes.draw do
  root to: "custom_pages#index"

  scope "(:locale)", locales: "/pt-BR|en/" do
    resources :stories, except: :index do
  #    put 'stories/auto_save', as: :auto_save_story_path
      get 'read', to: 'stories#read', as: 'read'
  #    put 'auto_save', on: :collection
      get 'prelude'
      put 'update_tabs'
      get 'graph_json'
      get 'graph_json_show', on: :collection
      post 'node_update'
      get 'erase_image', as: 'erase_image'
      get 'edit_special_attributes', as: "edit_special_attributes"
      get 'edit_story', to: 'stories#edit_story', as: 'edit_story'
      get 'edit_items', as: "edit_items"
      get 'graph'
      post 'use_item', on: :collection
      get 'buy_item'
      get 'select_weapon'
      post 'publish'
      get 'search_result', as: 'search_result', on: :collection
      get 'detail', as: 'show'
      get 'update_chapter_number', as: 'update_chapter_number'
      resources :comments
      put :favorite, on: :member
      resources :chapters do
        put ':id', to: 'chapters#update', as: 'chapter_update', on: :collection
      end
    end

    resources :adventurers do
      put 'update_adventurer_status', on: :collection
    end

    devise_for :users, controllers: { registrations: 'users/registrations' }
    
    get 'profile/:id' => 'users#profile', as: 'profile'


    get 'contato' => 'custom_pages#contact', as: 'contact'
    get 'send' => 'custom_pages#send_message', as: 'send_message'
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  about_me               :text
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :adventurers, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite_stories, dependent: :destroy
  has_many :favorites, through: :favorite_stories, source: :story
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

    # custom logic
    if params[:user][:password].present?
      result = resource.update_with_password(params[resource_name])
    else
      result = resource.update_without_password(params[resource_name].permit(:about_me))
    end

    # standart devise behaviour
    if result
      if is_navigational_format?
        if resource.respond_to?(:pending_reconfirmation?) && resource.pending_reconfirmation?
          flash_key = :update_needs_confirmation
        end
        set_flash_message :notice, flash_key || :updated
      end
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:sign_up) << :about_me
      devise_parameter_sanitizer.for(:account_update) << :name
      devise_parameter_sanitizer.for(:account_update) << :about_me
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def profile
    @user = User.find(params[:id])
    @stories = @user.stories
    @stories = @user.stories.published if current_user != @user
    @favorites = @user.favorites.published
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<div class="container">
  <div class="row profile">
    <div class="col-lg-12 col-sm-12 col-xs-12">
      <h1><%= @user.name %></h1>
      <h2><%= t "profile.autor_title" %></h2>
      <div class="about_me">
        <%= simple_format @user.about_me %>
      </div>
    </div>
  </div>
  <div class="row">
    <div id="profile-tabs">
      <ul>
        <% if @user == current_user %>
          <li><a href="#tabs-1"><%= t "profile.my_stories" %></a></li>
        <% else %>
          <li><a href="#tabs-1"><%= t "profile.stories" %></a></li>
        <% end %>
        <li><a href="#tabs-2"><%= t "profile.favourites" %></a></li>
      </ul>
      <div id="tabs-1">
        <% if @user == current_user %>
          <h2><%= t "profile.my_stories" %></h2>
        <% else %>
          <h2><%= t "profile.stories" %></h2>
        <% end %>

        <% if @stories.present? %>
          <% @stories.each do |story| %>
            <div class="row">
              <div class="col-lg-4 col-sm-12">
                <div>
                  <h3><%= story.title %> - by <%= story.user.name %></h3>
                  <%= image_tag story.cover(:index_cover), class: "img-responsive" %>
                  <div class="actions">
                    <div class="row">
                      <%= link_to story_show_path(story), class: 'btn btn-primary btn-action' do %>
                        <i class="fa fa-play"></i> <%= t('actions.read') %>
                      <% end %>
                    </div>
                    <div class="row">
                      <%= link_to edit_story_path(story), class: "btn btn-primary btn-action" do %>
                        <i class="fa fa-pencil-square-o"></i> <%= t('actions.edit') %>
                      <% end if story.user == current_user %>
                    </div>
                    <div class="row">
                      <%= link_to story, class: "btn btn-danger btn-action", data: {confirm: t("are_you_sure")}, :method => :delete do %>
                        <i class="fa fa-trash-o"></i> <%= t('actions.destroy') %>
                      <% end if story.user == current_user %>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-8 col-sm-12">
                <div class="resume">
                  <p>
                    <%= simple_format story.resume %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p><%= t('stories.index.no_stories') %></p>
        <% end %>
      </div>
      <div id="tabs-2">
        <h2><%= t "profile.favourites" %></h2>

        <% @favorites.each do |favorite| %>
          <div class="row">
            <div class="col-lg-4 col-sm-12">
              <div>
                <h3><%= favorite.title %> - by <%= link_to favorite.user.name, profile_path(favorite.user) %></h3>
                <%= image_tag favorite.cover(:index_cover), class: "img-responsive" %>
                <div class="actions">
                  <div class="row">
                    <%= link_to story_show_path(favorite), class: 'btn btn-primary btn-action' do %>
                      <i class="fa fa-play"></i> <%= t('actions.read') %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-8 col-sm-12">
              <div class="resume">
                <p>
                  <%= simple_format favorite.resume %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    $("#profile-tabs").tabs();
  });
</script>