config/routes.rb
Calabouco::Application.routes.draw do
  root to: "custom_pages#index"

  scope "(:locale)", locales: "/pt-BR|en/" do
    resources :stories, except: :index do
  #    put 'stories/auto_save', as: :auto_save_story_path
      get 'read', to: 'stories#read', as: 'read'
  #    put 'auto_save', on: :collection
      get 'prelude'
      put 'update_tabs'
      get 'graph_json'
      get 'graph_json_show', on: :collection
      post 'node_update'
      get 'erase_image', as: 'erase_image'
      get 'edit_special_attributes', as: "edit_special_attributes"
      get 'edit_story', to: 'stories#edit_story', as: 'edit_story'
      get 'edit_items', as: "edit_items"
      get 'graph'
      post 'use_item', on: :collection
      get 'buy_item'
      get 'select_weapon'
      post 'publish'
      get 'search_result', as: 'search_result', on: :collection
      get 'detail', as: 'show'
      get 'update_chapter_number', as: 'update_chapter_number'
      resources :comments
      put :favorite, on: :member
      resources :chapters do
        put ':id', to: 'chapters#update', as: 'chapter_update', on: :collection
      end
    end

    resources :adventurers do
      put 'update_adventurer_status', on: :collection
    end

    devise_for :users, controllers: { registrations: 'users/registrations' }
    
    get 'profile/:id' => 'users#profile', as: 'profile'


    get 'contato' => 'custom_pages#contact', as: 'contact'
    get 'send' => 'custom_pages#send_message', as: 'send_message'
  end

end

app/models/story.rb
# == Schema Information
#
# Table name: stories
#
#  id                 :integer          not null, primary key
#  title              :string(40)
#  resume             :text
#  user_id            :integer
#  created_at         :datetime
#  updated_at         :datetime
#  prelude            :text
#  cover              :string(255)
#  cover_file_name    :string(255)
#  cover_content_type :string(255)
#  cover_file_size    :integer
#  cover_updated_at   :datetime
#  published          :boolean          default(FALSE)
#  chapter_numbers    :integer
#  initial_gold       :integer          default(0)
#

class Story < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :title, use: [:slugged, :finders]

  before_destroy :destroy_favorites

  has_attached_file :cover, styles: {thumbnail: "200x200>", index_cover: "400x300>"}, :default_url => "no_image_:style.png"

  validates :title, presence: true
  validates :resume, presence: true
  validates :chapter_numbers, presence: true, numericality: true
  validates_attachment_size :cover, :less_than => 2.megabytes
  validates_attachment_content_type :cover, content_type: ["image/jpg", "image/png", "image/gif", "image/jpeg"]

  belongs_to :user
  has_many :adventurers, dependent: :destroy
  has_many :chapters, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :comments
  has_many :favorite_stories
  has_many :favorited_by, through: :favorite_stories, source: :user
  accepts_nested_attributes_for :chapters, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :items, reject_if: :all_blank, allow_destroy: true

  scope :by_user, -> (user_id) { where(user_id: user_id) }
  scope :published, -> { where(published: true) }

  def weapons
    items.weapons
  end

  def usable_items
    items.usable_items
  end

  def key_items
    items.key_items
  end

  def has_adventurer? adventurers
    adventurers.any? {|adventurer| adventurer.story == self}
  end

  def build_chapters chapter_numbers
    for i in (1..chapter_numbers)
      chapter = self.chapters.build
      chapter.decisions.build
      chapter.reference = i
      chapter.save
    end
  end

  def self.graph(chapters)
    chapters_with_decisions = {
      references: chapters.get_references,
      chapter_destinies: chapters.get_destinies,
      not_used: chapters.get_not_used_references
    }
    chapters_with_decisions[:valid] = Chapter.validate_chapters(chapters_with_decisions)
    chapters_with_decisions
  end

  def self.search(search)
    joins('LEFT JOIN users AS u 
            ON u.id = stories.user_id').where('u.name LIKE :search 
            OR stories.title LIKE :search', search: "%#{search}%").order('stories.title ASC') if search
  end

  def destroy_favorites
    favorites_to_destroy = FavoriteStory.where(story_id: self.id)
    favorites_to_destroy.destroy_all
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  include ChapterExtension
  include AdventurerExtension

  # before_filter :authenticate_user!, except: [:prelude, :read, :search, :index]
  # load_and_authorize_resource except: [:prelude, :read]
  before_filter :authenticate_user!, except: [:search_result, :detail]
  load_and_authorize_resource except: [:search_result, :favorite, :detail]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.by_user(current_user.id).page(params[:page]).per(5)
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])
    @items = @story.items
    @chapters = @story.chapters.includes(:decisions)
  end

  def detail
    @story = Story.find(params[:story_id])
  end

  def prelude
    @story = Story.find(params[:story_id])
    if @story.published || @story.user == current_user
      @adventurer = Adventurer.by_user_and_story(current_user, @story).first
      if params[:new_story]
        @adventurer = Adventurer.clear_or_create_adventurer(@adventurer, params[:story_id])
      else
        redirect_to story_read_path(@story, continue: true, chapter_id: @adventurer.chapter.id, adventurer_id: @adventurer.id)
      end
    else
      redirect_to root_url, alert: I18n.t('actions.not_published')
    end
  end

  def read
    @story = Story.find_by(slug: params[:story_id])
    if @story.try(:published) || @story.try(:user) == current_user
      if params[:continue]
        @chapter = Chapter.find(params[:chapter_id])
        @adventurer = Adventurer.find(params[:adventurer_id])
        @adventurers_items = AdventurerItem.by_adventurer(@adventurer)
      else
        @chapter = @story.chapters.find_by reference: params[:reference]
        if @story && @story.has_adventurer?(current_user.adventurers) && @chapter.present?
          set_gold_items_and_attributes(current_user)
          this_decision = Decision.find_by(destiny_num: @chapter.id)
          @adventurer.use_required_item(this_decision)
        else
          redirect_to root_url, alert: I18n.t('actions.not_found')
        end
      end
    else
      redirect_to root_url, alert: I18n.t('actions.not_published')
    end
  end

  def search_result
    @stories = Story.search(params[:search]).published.page(params[:page]).per(5)
  end

  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    chapter_numbers = params[:chapter_numbers].to_i
    @story = Story.includes(:chapters, :items).find(params[:id])

    generate_chapters(chapter_numbers)
    @chapter_count = @story.chapters.count
    @chapters = @story.chapters.page(params[:page]).per(10)
    @all_chapters = @story.chapters
    @page = params[:page]
    params[:change_page] == 'true' ? @last_chapter = nil : @last_chapter = params[:last_chapter]
  end

  def edit_story
    @story = Story.find(params[:story_id])
  end

  def edit_items
    @story = Story.find(params[:story_id])
    if @story.items.empty?
      item = @story.items.build
    end
  end

  def favorite
    type = params[:type]
    story = Story.find(params[:id])
    if type == "favorite"
      current_user.favorites << story
      redirect_to :back, notice: "Você favoritou #{story.title}"
    elsif type == "unfavorite"
      current_user.favorites.delete(story)
      redirect_to :back, notice: "Você deixou de favoritar #{story.title}"
    else
      redirect_to :back, notice: 'Nada aconteceu.'
    end
  end

  def update_chapter_number
    @story = Story.find(params[:story_id])

    quantity = params[:quantity].to_i

    params[:type] == 'sum' ? add_chapters(@story, quantity) : remove_chapters(@story, quantity)
  end

  def graph
    @story = Story.find(params[:story_id])
  end

  def graph_json
    chapters = Chapter.includes(:decisions).by_story(params[:id])
    @chapters = Story.graph(chapters)

    respond_to do |format|
      format.json { render json: @chapters.to_json }
    end
  end

  def graph_json_show
    chapters_of_story = Chapter.by_story(params[:id])
    chapters = chapters_of_story.includes(:decisions)

    @chapters = Story.graph(chapters)

    respond_to do |format|
      format.json { render json: @chapters.to_json }
    end
  end

  def node_update
    chapter = Chapter.by_story(params[:id]).where(reference: params[:cap].gsub("Cap ","")).first
    chapter.x = params[:x].to_f
    chapter.y = params[:y].to_f

    respond_to do |format|
      if chapter.save
        format.html { render nothing: true, notice: 'Update SUCCESSFUL!', status: 200 }
      else
        format.json { render nothing: true, status: 500 }
      end
    end
  end

  def use_item
    adventurer = current_user.adventurers.by_story(params[:story_id]).first
    result = adventurer.use_item(params["item-id"], params[:attribute], params[:modifier])

    if result.present?
      result[:message] = I18n.t('actions.messages.adventurer_update_success')
    else
      result[:message] = I18n.t('actions.messages.adventurer_update_fail')
    end

    respond_to do |format|
      format.json { render json: result.to_json }
    end
  end

  def buy_item
    adventurer = current_user.adventurers.where(story_id: params[:story_id]).first
    modifier_shop = ModifierShop.find(params[:shop_id])
    item = modifier_shop.item
    adventurer_modifier_shop = adventurer.adventurers_shops.where(modifier_shop_id: params[:shop_id]).first

    if adventurer.adventurer_modifier_shop_present? params[:shop_id]
      update_same_adventurer_shop(adventurer, adventurer_modifier_shop, modifier_shop, item)
    else
      create_new_adventurer_shop(adventurer, adventurer_modifier_shop, modifier_shop, item, params[:shop_id])
    end
  end

  def select_weapon
    adventurer = Adventurer.find params[:adventurer_id]
    if adventurer.select_weapon(params[:item_id])
      redirect_to :back, notice: I18n.t('actions.success_weapon_select')
    else
      redirect_to :back, alert: I18n.t('actions.fail_weapon_select')
    end
  end

  def erase_image
    current_chapter = Chapter.find(params[:chapter_id])
    current_chapter.image_file_name = nil
    current_chapter.image_content_type = nil
    current_chapter.image_file_size = 0
    current_chapter.save

    render nothing: true
  end

  def publish
    story = Story.find(params[:story_id])
    publish_story(story)
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to edit_story_path(id: @story, chapter_numbers: params[:story][:chapter_numbers]), notice: I18n.t('actions.messages.create_success') }
        format.json { render json: @story, status: :created, location: @story }
      else
        @errors = get_errors(@story)
        format.html { redirect_to new_story_path, alert: {errors: @errors} }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_tabs
    @story = Story.find(params[:story_id].to_i)

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { render nothing: true}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    if @story.update_attributes(story_params)
      redirect_story(@story, params)
    else
      @chapters = @story.chapters
      @errors = get_errors(@story)
      flash[:alert] = {errors: @errors}
      respond_to do |format|
        case params[:commit]
        when t('actions.edit_items')
          @errors = get_errors(@story)

          format.html { render action: :edit_items, controller: :stories, alert: @errors }
          format.json { render json: {errors: @errors.to_json,
                                      chapters_with_errors: @chapters_with_errors},
                                      status: :unprocessable_entity }
        when t('actions.save_story')
          @chapters_with_errors = get_chapters_with_errors(@story)
          format.html { render action: :edit_story, controller: :stories, alert: @errors }
          format.json { render json: {errors: @errors.to_json,
                                      chapters_with_errors: @chapters_with_errors},
                                      status: :unprocessable_entity }
        end
      end
    end
  end

  def auto_save
    @story = Story.find(params[:story_id].to_i)

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { render nothing: true}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to profile_path(current_user) }
      format.json { head :no_content }
    end
  end

  private

    def publish_story(story)
      if story.published
        story.published = false
      else
        story.published = true
      end

      if story.save
        data = format_publish_message(story, success: true)
      else
        data = format_publish_message(story, success: true)
      end

      respond_to do |format|
        format.json { render json: data.to_json }
      end
    end

    def redirect_story(story, params)
      case params[:commit]
        when I18n.t('actions.save')
          redirect_to :back, notice: I18n.t('actions.messages.save_success')
        when I18n.t('actions.edit_items')
          redirect_to story_edit_items_path(story), notice: I18n.t('actions.messages.data_saved')
        when I18n.t('actions.save_story')

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= render partial: 'shared/errors' %>
<div class="message-container">
  
</div>
<div class="row">
  <div class="col-lg-12">
    <% index = 0 %>
    <% @chapters.each do |chapter| %>
      <div class="chapter-fields wrapper <%= index.to_s == @last_chapter ? 'active' : '' %>">
        <div class="accordionButton">
          <h3><%= t('stories.edit.chapter') %> <%= chapter.reference %></h3>
        </div>
        <div class="accordionContent">
          <%= simple_form_for chapter, url: chapter_update_story_chapters_path(@story, chapter) do |f| %>
            <div class="form-group">
              <%= f.input :content, label: t('stories.edit.content'), input_html: { rows: 10, title: t('tooltip.chapter_content'), class: 'chapter-content-wysiwyg summernote form-control' } %>
            </div>
            <%= f.input :image, label: t('stories.edit.image'), hint: t('actions.messages.image_hint'), input_html: {onchange: "validateFiles(this);"}, data: {max_file_size: 2.megabytes} %>
            <% if f.object.image.blank? %>
              <%= t('stories.edit.no_current_image') %>
            <% else %>
              <div class="chapter-image">
                <%= t('stories.edit.current_image') %>: <%= image_tag Chapter.find(f.object.id).image(:thumbnail) %>
              </div>
              <%= f.input :id, as: :hidden %>
              <p><%= link_to t('stories.edit.remove_image'), "#", remote: true, class: "remove btn btn-primary" %></p>
            <% end %>
            <div class="decisions">
              <h3><%= t('stories.edit.decisions') %></h3>
              <%= f.simple_fields_for :decisions do |builder| %>
                <%= render partial: "/decisions/decisions_fields", :locals => {:f => builder} %>
              <% end %>
              <%= link_to_add_fields t('stories.edit.add_decisions'), f, :decisions, "decisions" %>
            </div>
            <div class="monsters">
              <h3><%= t('stories.edit.monsters') %></h3>
              <%= f.simple_fields_for :monsters do |builder| %>
                <%= render partial: "/monsters/monsters_fields", :locals => {:f => builder} %>
              <% end %>
              <%= link_to_add_fields t('stories.edit.add_monsters'), f, :monsters, "monsters" %>
            </div>
            <div class="modifiers-items">
              <h3><%= t('stories.edit.items') %></h3>
              <%= f.simple_fields_for :modifiers_items do |builder| %>
                <%= render "/modifiers_items/modifiers_items_fields", f: builder %>
              <% end %>
              <%= link_to_add_fields t('stories.edit.add_item'), f, :modifiers_items, "modifiers_items" %>
            </div>
            <div class="modifiers-attributes">
              <h3><%= t('stories.edit.attribute_modifiers') %></h3>
              <%= f.simple_fields_for :modifiers_attributes do |builder| %>
                <%= render "/modifiers_attributes/modifiers_attributes_fields", f: builder %>
              <% end %>
              <%= link_to_add_fields t('stories.edit.add_modifier'), f, :modifiers_attributes, "modifiers_attributes" %>
            </div>
            <div class="modifiers-shops">
              <h3><%= t('stories.edit.shop') %></h3>
              <%= f.simple_fields_for :modifiers_shops do |builder| %>
                <%= render "modifiers_shops/modifiers_shops_fields", f: builder %>
              <% end %>
              <%= link_to_add_fields t('stories.edit.add_item'), f, :modifiers_shops, "modifiers_shops"%>
            </div>

            <%= f.hidden_field :page, value: @page %>
            <%= f.hidden_field :position, value: index %>
            <% index += 1 %>

            <div class="form-action">
              <%= f.submit 'Salvar', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
      <br/>

    <% end %>

    <%= paginate @chapters, params: {change_page: true} %>
  </div>
</div>
<%= render partial: 'publish_script' %>
<script>
  $(document).ready(function(){
    $('.chapter-fields').accordion({
      active: false,
      collapsible: true,
      header: '.accordionButton',
      heightStyle: "content",
      autoHeight: false,
      clearStyle: true,
    });

    $('.active').accordion('option','active',0);
  });
</script>
 

app/views/stories/detail.html.erb
<%= render partial: "/shared/modal" %>

<%= content_for :metadata do %>
  <meta name="description" content="<%= @story.resume.truncate(100) %>">
  <meta name="author" content="<%= @story.user.name %>">
<% end %>
<%= content_for :opengraph do %>
  <meta property="og:title" content="<%= @story.title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= story_show_url(@story) %>" />
  <meta property="og:image" content="<%= root_url[0..-2] + @story.cover(:index_cover) %>" />
  <meta property="og:description" content="<%= @story.resume.truncate(100) %>" />
  <meta property="og:site_name" content="<%= @story.title %>" />
  <meta property="og:locale" content="pt_br" />
<% end %>

<div class="container prelude_div">
  <div class="row">
    <div class="col-lg-4">
      <div class="image">
        <%= image_tag @story.cover(:index_cover), class: "img-responsive center" %>
      </div>      
    </div>
    <div class="col-lg-8">
      <h3><%= t('stories.prelude.title') %></h3>

      <% if current_user && @story.user != current_user %>
        <% if current_user.favorites.include?(@story) %>
          <%= link_to "", favorite_story_path(@story, type: "unfavorite"), method: :put, class: 'btn btn-primary fa fa-star' %>
        <% else %>
          <%= link_to "", favorite_story_path(@story, type: "favorite"), method: :put, class: 'btn btn-primary favorite fa fa-star-o' %>
        <% end %>
      <% end %>

      <div class="resume">
        <% unless @story.resume.empty? %>
          <%= simple_format @story.resume %>
        <% end %>

        <% if current_user and @story.has_adventurer? current_user.adventurers %>
          <%= link_to t('actions.read'), "javascript:;", class: "read btn btn-primary btn-action", data: {continue: true, story_id: @story.slug} %>
        <% else %>
          <%= link_to t('actions.read'), story_prelude_path(@story, new_story: true), class: "btn btn-primary btn-action", data: {continue: false} %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h2><%= t "detail.comments" %></h2>
      <% @story.comments.each do |comment| %>
        <div class="comment">
          <div class="comment-author">
            <% if comment.user %>
              <p>Autor: <%= link_to comment.user.name, profile_path(comment.user) %></p>
            <% else %>
              <p>Autor: Not found</p>
            <% end %>
          </div>
          <div class="comment-content">
            <p><%= comment.content.gsub(/\n/, '<br/>').html_safe %></p>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 comment-form">
      <%= simple_form_for([@story, @story.comments.build]) do |f| %>
        <div class="form-group">
          <%= f.input :content, label: t("detail.new_comment"), input_html: { rows: 10, class: 'form-control' } %>
        </div>
        <div class="form-group">
          <%= f.submit t("detail.create_comment"), class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stories/edit.html.erb
<div class="container">

  <%= render 'shared/navigation' %>
  <h1><%= t('stories.edit.title') %></h1>
  <h2><%= "#{@chapter_count} " %> <%= "#{t('stories.edit.chapters')}".pluralize(@chapter_count) %></h2>

  <%= render 'form' %>  
</div>

app/views/stories/index.html.erb
<%= render partial: "/shared/modal" %>

<div class="container stories">
  <h1><%= t('stories.index.title') %></h1>
  <% if @stories.empty? %>
    <p><%= t('stories.index.no_stories') %></p>
  <% else %>
    <%= paginate @stories %>

    <% @stories.each do |story| %>
      <div class="story_div">
        <div class="row">
          <div class="col-lg-4 col-sm-12">
            <div class="image">
              <h3><%= story.title %> - by <%= story.user.name %></h3>
              <%= image_tag story.cover(:index_cover), class: "img-responsive" %>
              <div class="actions">
                <div class="row">
                  <div class="col-lg-5">
                    <%= link_to t('actions.show'), story, class: "btn btn-primary" if story.user == current_user %>
                  </div>
                  <div class="col-lg-5">
                    <% if current_user and story.has_adventurer? current_user.adventurers %>
                        <%= link_to t('actions.read'), "javascript:;", class: "read btn btn-primary", data: {continue: true, story_id: story.id} %>
                      <% else %>
                        <%= link_to t('actions.read'), story_prelude_path(story, new_story: true), class: "btn btn-primary", data: {continue: false} %>
                      <% end %>
                  </div>
                </div>
                <div class="row">
                  <div class="col-lg-5">
                    <%= link_to t('actions.edit'), edit_story_path(story), class: "btn btn-primary" if story.user == current_user %>
                  </div>
                  <div class="col-lg-5">
                    <%= link_to t('actions.destroy'), story, class: "btn btn-danger", data: {confirm: 'Are you sure?'}, method: :delete if story.user == current_user %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-8 col-sm-12">
            <div class="prelude">
              <p>
                <%= simple_format story.resume %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <%= paginate @stories %>
  <% end %>
</div>

<br />

app/views/stories/new.html.erb
<div class="container">
  <h1><%= t('stories.new.title') %></h1>
  <%= render 'new_form' %>
</div>

app/views/stories/read.html.erb
<div class="container">
  <div class="message-container"></div>
  <div class="row">
    <div class="col-lg-9 col-sm-12 chapter">
      <h3><%= t('stories.read.chapter') %> <%= @chapter.reference %></h3>
      <div class="chapter-image">
        <p>
          <%= image_tag @chapter.image(:normal), class: "img-responsive center-block" if @chapter.image.present? %>
        </p>
      </div>
      <div class="chapter-content">
        <p>
          <%= simple_format @chapter.content %>
        </p>
      </div>
      <% if @chapter.modifiers_shops.present? %>
        <div id="chapter-shop">
          <h3>Comprar?</h3>
          <% @chapter.modifiers_shops.each do |shop| %>
            <p>
              <%= link_to_if(return_real_quantity(shop) > 0, shop.item.name, story_buy_item_path(@story.id, shop_id: shop.id)) %><br>
              <span class="shop-price">Preço: <%= shop.price %></span><br>
              <span class="shop-qty">Quantidade: <%= return_real_quantity(shop) %></span>
            </p>
          <% end %>
        </div>
      <% end %>
      <% if @chapter.monsters.present? %>
      <hr/>
        <% @chapter.monsters.each do |monster| %>
          <p>
            <%= t('stories.read.monster') %>: <%= monster.name %>
          </p>
          <p>
            <%= t('stories.read.skill') %>: <span id="<%= monster.name %>_skill"><%= monster.skill %></span>
          </p>
          <p>
            <%= t('stories.read.energy') %>: <span id="<%= monster.name %>_energy"><%= monster.energy %></span>
          </p>
          <hr/>
        <% end %>
        <p>
          <%= button_tag t('stories.read.combat'), class: "btn btn-primary", id: "combat" %>
        </p>
        <div id="combat-result"></div>
      <% end %>
      <div id="chapter-buttons">
        <% @chapter.decisions.where.not(destiny_num: nil).each do |decision| %>
          <% reference = decision.destiny.reference if decision.destiny %>
          <% disabled = "disabled" if @chapter.monsters.present? %>
          <% donthave = false %>
          <% donthave = true if decision.item_validator && @adventurer.dont_have_item(decision.item) %>
          <% if decision.item_validator? %>
            <% disabled ||= "disabled" if @adventurer.dont_have_item(decision.item) %>
          <% end %>
          <p>
            <%= link_to  "#{t('stories.read.chapter')} #{decision.destiny.reference}",
              story_read_path(@story, reference: reference),
              class: "btn btn-primary #{disabled}", data: {donthave: "#{donthave}" }  if decision.destiny %>
          </p>
        <% end %>
      </div>
    </div>
    <% if @adventurer.present? %>
      <%= render partial: 'adventurers/adventurer' %>
    <% end %>
  </div>
</div>

<%= render partial: 'combat_script' %>

app/views/stories/story.html.erb
<%= render partial: "/shared/modal" %>

<div class="container prelude_div">
  <div class="row">
    <div class="col-lg-4">
      <div class="image">
        <%= image_tag @story.cover(:index_cover), class: "img-responsive center" %>
      </div>      
    </div>
    <div class="col-lg-8">
      <h3><%= t('stories.prelude.title') %></h3>

      <% if current_user && @story.user != current_user %>
        <% if current_user.favorites.include?(@story) %>
          <%= link_to "", favorite_story_path(@story, type: "unfavorite"), method: :put, class: 'btn btn-primary fa fa-star' %>
        <% else %>
          <%= link_to "", favorite_story_path(@story, type: "favorite"), method: :put, class: 'btn btn-primary favorite fa fa-star-o' %>
        <% end %>
      <% end %>

      <div class="resume">
        <% unless @story.resume.empty? %>
          <%= simple_format @story.resume %>
        <% end %>

        <% if current_user and @story.has_adventurer? current_user.adventurers %>
          <%= link_to t('actions.read'), "javascript:;", class: "read btn btn-primary btn-action", data: {continue: true, story_id: @story.id} %>
        <% else %>
          <%= link_to t('actions.read'), story_prelude_path(@story, new_story: true), class: "btn btn-primary btn-action", data: {continue: false} %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h2>Comentários</h2>
      <% @story.comments.each do |comment| %>
        <div class="comment">
          <div class="comment-author">
            <% if comment.user %>
              <p>Autor: <%= link_to comment.user.name, profile_path(comment.user) %></p>
            <% else %>
              <p>Autor: Not found</p>
            <% end %>
          </div>
          <div class="comment-content">
            <p><%= comment.content.gsub(/\n/, '<br/>').html_safe %></p>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12 comment-form">
      <%= simple_form_for([@story, @story.comments.build]) do |f| %>
        <div class="form-group">
          <%= f.input :content, label: "Novo comentário", input_html: { rows: 10, class: 'form-control' } %>
        </div>
        <div class="form-group">
          <%= f.submit "Criar comentário", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>