config/routes.rb
Calabouco::Application.routes.draw do
  root to: "custom_pages#index"

  scope "(:locale)", locales: "/pt-BR|en/" do
    resources :stories, except: :index do
  #    put 'stories/auto_save', as: :auto_save_story_path
      get 'read', to: 'stories#read', as: 'read'
  #    put 'auto_save', on: :collection
      get 'prelude'
      put 'update_tabs'
      get 'graph_json'
      get 'graph_json_show', on: :collection
      post 'node_update'
      get 'erase_image', as: 'erase_image'
      get 'edit_special_attributes', as: "edit_special_attributes"
      get 'edit_story', to: 'stories#edit_story', as: 'edit_story'
      get 'edit_items', as: "edit_items"
      get 'graph'
      post 'use_item', on: :collection
      get 'buy_item'
      get 'select_weapon'
      post 'publish'
      get 'search_result', as: 'search_result', on: :collection
      get 'detail', as: 'show'
      get 'update_chapter_number', as: 'update_chapter_number'
      resources :comments
      put :favorite, on: :member
      resources :chapters do
        put ':id', to: 'chapters#update', as: 'chapter_update', on: :collection
      end
    end

    resources :adventurers do
      put 'update_adventurer_status', on: :collection
    end

    devise_for :users, controllers: { registrations: 'users/registrations' }
    
    get 'profile/:id' => 'users#profile', as: 'profile'


    get 'contato' => 'custom_pages#contact', as: 'contact'
    get 'send' => 'custom_pages#send_message', as: 'send_message'
  end

end

app/controllers/custom_pages_controller.rb
class CustomPagesController < ApplicationController
  def index
    @stories = Story.published.last(8)
  end

  def contact

  end

  def send_message
    unless params[:email].empty? && params[:message].empty? && params[:howdy].nil?
      ContactMailer.contact_email(params).deliver
      redirect_to :back, notice: "Contato enviado!"
    else
      redirect_to :back, alert: "Preencha corretamente os dados."
    end
  end
end

app/helpers/custom_pages_helper.rb
module CustomPagesHelper
end

app/views/custom_pages/contact.html.erb
<div class="container">
  <div class="row row-centered">
    <h1><%= t "contact.contact" %></h1>
    <div class="col-lg-4 col-centered">
      <p><%= t "contact.find_bug" %></p>
      <%= form_tag send_message_path, method: :get, id: 'contact-form' do %>
        <div class="errors"></div>
        <div class="form-inputs">
          <div class="form-group">
            <%= label_tag 'Email' %>
            <%= text_field_tag :email, nil, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= label_tag 'Mensagem' %>
            <%= text_area_tag :message, nil, class: 'form-control', rows: 15 %>
          </div>

          <div id="check"></div>
        </div>

        <div class="form-actions">
          <%= submit_tag "Enviar", class: 'btn btn-primary btn-lg', id: 'contact-submit' %>
        </div>
      <% end %>
    </div>
  </div>
    
</div>

app/views/custom_pages/index.html.erb
<%= render partial: "/shared/modal" %>

<div class="header">
  <div class="container">
    <div class="header-content">
      <h1>Dungeon Masters</h1>
    </div>
  </div>
</div>
<div class="features">
  <% unless user_signed_in? %>
    <div class="feature">
      <div class="container">
        <div class="row feature-content">
          <div class="col-lg-6">
            <%= image_tag "create_chapters.png", class: "img-responsive" %>
          </div>
          <div class="col-lg-6">
            <h2><%= t('custom_pages.feature1') %></h2>
            <p><%= t('custom_pages.description_1') %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="feature feature-odd">
      <div class="container">
        <div class="row feature-content">
          <div class="col-lg-6">
            <h2><%= t('custom_pages.feature2') %></h2>
            <p><%= t('custom_pages.description_2') %></p>
          </div>
          <div class="col-lg-6">
            <%= image_tag "create_decisions.png", class: "img-responsive" %>
          </div>
        </div>
      </div>
    </div>
    <div class="feature">
      <div class="container">
        <div class="row feature-content">
          <div class="col-lg-6">
            <%= image_tag "create_monsters.png", class: "img-responsive" %>
          </div>
          <div class="col-lg-6">
            <h2><%= t('custom_pages.feature3') %></h2>
            <p><%= t('custom_pages.description_3') %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="feature feature-odd">
      <div class="container">
        <div class="row feature-content">
          <div class="col-lg-6">
            <h2><%= t('custom_pages.feature4') %></h2>
            <p><%= t('custom_pages.description_4') %></p>
          </div>
          <div class="col-lg-6">
            <%= image_tag "create_items.png", class: "img-responsive" %>
          </div>
        </div>
      </div>
    </div>
    <div class="feature">
      <div class="container">
        <div class="row feature-content">
          <div class="col-lg-6">
            <%= image_tag "create_attributes.png", class: "img-responsive" %>
          </div>
          <div class="col-lg-6">
            <h2><%= t('custom_pages.feature5') %></h2>
            <p><%= t('custom_pages.description_5') %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="feature feature-odd">
      <div class="container">
        <div class="row feature-content">
          <div class="col-lg-6">
            <h2><%= t('custom_pages.feature6') %></h2>
            <p><%= t('custom_pages.description_6') %></p>
          </div>
          <div class="col-lg-6">
            <%= image_tag "graph.png", class: "img-responsive" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="feature">
    <div class="container">
      <h3><%= t('custom_pages.last_stories') %></h3>
      <% if @stories.empty? %>
        <p>No stories.</p>
      <% else %>
        <div class="row last-stories">
          <% @stories.each do |story| %>
            <div class="index_stories col-lg-3 col-sm-12">
              <p><%= link_to story.title, story_show_path(story), class: 'read' %></p>
              <%= image_tag story.cover(:thumbnail) %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>